### ISSUE TITLE
GUI question:  How to auto-populate the cover pane?

### ISSUE THREAD

**Issue by Geordon** [gonzoua/AudioBookBinder#20]
I have a bunch of stuff that I will be converting from MP3 to audiobooks.  I really like the fact that I can drag and drop a folder into the ABB window and it sorts the files in order by name and number.

Is there some way that I can name the cover image so that it auto-populates into the cover selection?  I know that the command line utility has an option to include a cover image.  However, naming a file "cover.jpg" doesn't do what I was hoping.  

Does anyone have any other suggestions?

**Comment by gonzoua** [comment]
There is no way to automate setting cover image currently. It always has to be set manually

**Comment by Geordon** [comment]
Ok, thank you!
