### ISSUE TITLE
Can I build the ABB app from this repository?

### ISSUE THREAD

**Issue by johnkgibson** [gonzoua/AudioBookBinder#40]
Is this built out as the Mac App Audiobook binder? It was my favorite tool for building audiobooks. I would love to be able to run this on MacOS again.

**Comment by gonzoua** [comment]
Should be buildable as of commit 223ba058da074632d5d79119d16a9f434d467b83:

```
git clone --recursive https://github.com/gonzoua/AudioBookBinder.git
cd AudioBookBinder
xcodebuild -target abbinder -target AudioBookBinder
ls -al build/Debug
```

**Comment by johnkgibson** [comment]
AWESOME!
  
  

  
>
