### ISSUE TITLE
fatal error: 'mp4v2/mp4v2.h' file not found

### ISSUE THREAD

**Issue by AlexanderWillner** [gonzoua/AudioBookBinder#8]
Steps that will reproduce the problem?
1. git clone --recursive https://github.com/gonzoua/AudioBookBinder.git
2. cd AudioBookBinder
3. xcodebuild -project AudioBookBinder.xcodeproj

What is the expected result?
Binary.

What happens instead?
Fatal error: 'mp4v2/mp4v2.h' file not found.

Possible workaround:
Search the internet for this file, maybe. Not tried.

**Comment by skopanev** [comment]
Hi everyone. Could you help to use it? 

I see it says it is a submodule, but doesn't work. 
Can't build it... Thx!

**Comment by gonzoua** [comment]
Should be buildable as of commit 223ba058da074632d5d79119d16a9f434d467b83:

```
git clone --recursive https://github.com/gonzoua/AudioBookBinder.git
cd AudioBookBinder
xcodebuild -target abbinder -target AudioBookBinder
ls -al build/Debug
```
